services:
  django:
    build: ./app
    command: bash -c 'while !</dev/tcp/postgres-db/5432; do sleep 1; done; python manage.py makemigrations --noinput; python manage.py makemigrations feedbackApp --noinput; python manage.py migrate --noinput; python manage.py collectstatic --noinput; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app:/app
      - django_media:/media
      - django_password:/passwords
    expose:
      - 8000
    environment:
      - DEBUG=1
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@postgres-db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgres-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`)"
  postgres-db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
  traefik:
    image: traefik:v3.1.2
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
  django_media:
  django_password: